"""updating bio for iteration

Revision ID: 9e25d7392e3a
Revises: 1837077807ac
Create Date: 2020-12-05 17:33:58.717989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e25d7392e3a'
down_revision = '1837077807ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bio_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_index(batch_op.f('ix_bio_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
