"""updating bio

Revision ID: 1cf6901ea903
Revises: 1837077807ac
Create Date: 2021-01-03 16:20:41.351378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf6901ea903'
down_revision = '1837077807ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=3000), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bio_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_index(batch_op.f('ix_bio_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
