"""empty message

Revision ID: 2356ebe38055
Revises: 1cf6901ea903
Create Date: 2021-01-10 13:06:11.397011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2356ebe38055'
down_revision = '1cf6901ea903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=30000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_timestamp'))

    op.drop_table('releases')
    # ### end Alembic commands ###
