"""empty message

Revision ID: c85c0316f630
Revises: fc00ad4c8b3b
Create Date: 2021-01-16 10:53:38.637188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85c0316f630'
down_revision = 'fc00ad4c8b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('podcasts', sa.String(length=30000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('podcasts')

    # ### end Alembic commands ###
