"""empty message

Revision ID: fc00ad4c8b3b
Revises: 2356ebe38055
Create Date: 2021-01-10 13:50:27.653189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc00ad4c8b3b'
down_revision = '2356ebe38055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=3000), nullable=True),
    sa.Column('releases', sa.String(length=30000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('bio', schema=None) as batch_op:
        batch_op.drop_index('ix_bio_timestamp')

    op.drop_table('bio')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index('ix_releases_timestamp')

    op.drop_table('releases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=30000), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index('ix_releases_timestamp', ['timestamp'], unique=False)

    op.create_table('bio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=3000), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bio', schema=None) as batch_op:
        batch_op.create_index('ix_bio_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_timestamp'))

    op.drop_table('content')
    # ### end Alembic commands ###
